// mp-vehicle.js v2.8.0 — Open System modifier, maneuver vehicle-level, tooltips

class Vehicle {
  constructor() {
    this.name = "";
    this.model = "";
    this.operator = "";
    this.basicCost = 15;
    this.techMod = 0;
    this.maneuverMod = 0;
    this.wontExplode = false;
    this.isBase = false;
    this.systems = [];
    this.keyEntries = [];
    this.pictureData = "";
    this._nextId = 1;
    this._nextKeyId = 1;
  }

  get chassis() { return MP.lookupChassis(this.basicCost); }
  get totalSpaces() { return this.chassis.sp; }
  get allocatedSpaces() { return this.systems.reduce((s, sys) => s + (sys.spaces || 0), 0); }
  get remainingSpaces() { return this.totalSpaces - this.allocatedSpaces; }

  addSystem() {
    const sys = {
      id: this._nextId++,
      spaces: 0, extraCPs: 0, desc: "", dmg: "",
      cells: [],
      integral: false, bulky: 0, delicate: 0, open: false,
      adjST: 0, adjEN: 0, adjAG: 0, adjIN: 0, adjCL: 0,
    };
    this.systems.push(sys);
    return sys;
  }

  removeSystem(id) { this.systems = this.systems.filter(s => s.id !== id); }
  findSystem(id) { return this.systems.find(s => s.id === id) || null; }

  paintCell(sysId, gx, gy) {
    const sys = this.findSystem(sysId);
    if (!sys || sys.cells.length >= sys.spaces || this.cellAt(gx, gy)) return false;
    sys.cells.push({ gx, gy });
    return true;
  }

  unpaintCell(gx, gy) {
    for (const sys of this.systems) {
      const idx = sys.cells.findIndex(c => c.gx === gx && c.gy === gy);
      if (idx >= 0) { sys.cells.splice(idx, 1); return sys; }
    }
    return null;
  }

  cellAt(gx, gy) {
    for (const sys of this.systems)
      if (sys.cells.some(c => c.gx === gx && c.gy === gy)) return sys;
    return null;
  }

  addKeyEntry(label, desc) {
    const entry = { id: this._nextKeyId++, label: label || "", desc: desc || "" };
    this.keyEntries.push(entry);
    return entry;
  }
  removeKeyEntry(id) { this.keyEntries = this.keyEntries.filter(k => k.id !== id); }

  // CPs generated by system spaces
  sysBaseCPs(sys) {
    if (!sys.spaces) return 0;
    return MP.lookupSys(sys.spaces).cp;
  }

  // Total CPs for the system after all modifiers
  sysCPs(sys) {
    let cp = this.sysBaseCPs(sys);
    cp += (sys.extraCPs || 0);
    cp += this.techMod;
    if (sys.integral) cp = Math.floor(cp / 2);
    if (sys.open) cp = Math.floor(cp / 4);
    return Math.max(0, cp);
  }

  sysHits(sys) {
    if (!sys.spaces) return 0;
    let hits = MP.lookupSys(sys.spaces).hits;
    hits += Math.ceil(4.3 * (sys.bulky || 0));
    hits -= Math.ceil(4.3 * (sys.delicate || 0));
    return Math.max(1, hits);
  }

  sysProfile(sys) {
    if (!sys.spaces) return 0;
    return MP.lookupSys(sys.spaces).prof;
  }

  sysProfileDisplay(sys) {
    const p = this.sysProfile(sys);
    if (!p) return "";
    return "x" + (Number.isInteger(p) ? p : p.toFixed(2).replace(/0+$/, "").replace(/\.$/, ""));
  }

  get baseCost() { return this.basicCost; }
  get systemExtraCPs() { return this.systems.reduce((sum, s) => sum + (s.extraCPs || 0), 0); }

  get totalCost() {
    let cost = this.baseCost + this.systemExtraCPs + this.techMod;
    cost += this.maneuverMod;
    if (this.wontExplode) cost += 5;
    for (const s of this.systems) {
      cost += (s.bulky || 0) * 2.5;
      cost -= (s.delicate || 0) * 2.5;
    }
    return cost;
  }

  get st() {
    let v = this.chassis.st;
    for (const s of this.systems) v += (s.adjST || 0);
    return v;
  }
  get en() {
    let v = this.chassis.en;
    for (const s of this.systems) v += (s.adjEN || 0);
    return v;
  }
  get ag() {
    let v = 9;
    for (const s of this.systems) v += (s.adjAG || 0);
    return v;
  }
  get intel() {
    let v = 0;
    for (const s of this.systems) v += (s.adjIN || 0);
    return v;
  }
  get cl() {
    let v = 9;
    for (const s of this.systems) v += (s.adjCL || 0);
    return v;
  }
  get hits() { return this.chassis.hits; }
  get power() { return this.st + this.en + this.ag + this.intel; }
  get handling() { return MP.save(this.ag) - 10; }
  get turnRate() { return 3 + (this.maneuverMod / 5); }
  get armor() { return { kin: 3, eng: 3, bio: 3, ent: 3, psy: 0 }; }
  get explosionDice() {
    if (this.wontExplode) return "None";
    const cp = Math.max(0, this.totalCost);
    const d8s = 1 + Math.floor(cp / 5);
    const rem = cp % 5;
    return rem > 0 ? d8s + "d8+1d4" : d8s + "d8";
  }
  get explosionArea() {
    const r = Math.ceil(this.chassis.prof);
    return r % 2 === 0 ? r + 1 : r;
  }
  get defense() { return this.handling; }

  toJSON() {
    return {
      version: 8, type: "mp-vehicle",
      name: this.name, model: this.model, operator: this.operator,
      basicCost: this.basicCost, techMod: this.techMod,
      maneuverMod: this.maneuverMod, wontExplode: this.wontExplode,
      isBase: this.isBase, systems: this.systems,
      keyEntries: this.keyEntries, pictureData: this.pictureData,
    };
  }

  fromJSON(data) {
    this.name = data.name || "";
    this.model = data.model || "";
    this.operator = data.operator || "";
    this.basicCost = data.basicCost ?? (data.chassisIdx != null ? MP.CHASSIS[data.chassisIdx]?.cp ?? 15 : 15);
    this.techMod = data.techMod || 0;
    this.maneuverMod = data.maneuverMod || 0;
    this.wontExplode = data.wontExplode || false;
    this.isBase = data.isBase || false;
    this.pictureData = data.pictureData || "";
    this.systems = (data.systems || []).map(s => {
      s.cells = s.cells || [];
      s.extraCPs = s.extraCPs || 0;
      s.integral = s.integral || false;
      s.bulky = s.bulky || 0; s.delicate = s.delicate || 0;
      s.open = s.open || false;
      s.adjST = s.adjST || 0; s.adjEN = s.adjEN || 0;
      s.adjAG = s.adjAG || 0; s.adjIN = s.adjIN || 0;
      s.adjCL = s.adjCL || 0;
      return s;
    });
    this.keyEntries = data.keyEntries || [];
    this._nextId = Math.max(1, ...this.systems.map(s => s.id), 0) + 1;
    this._nextKeyId = Math.max(1, ...this.keyEntries.map(k => k.id), 0) + 1;
  }

  toCSV() {
    const rows = [];
    rows.push(["Name", this.name]);
    rows.push(["Basic Cost", this.baseCost]);
    rows.push(["Total Cost", this.totalCost]);
    rows.push(["System Spaces", this.totalSpaces]);
    rows.push(["ST", this.st]); rows.push(["EN", this.en]);
    rows.push(["AG", this.ag]); rows.push(["IN", this.intel]); rows.push(["CL", this.cl]);
    rows.push([]);
    rows.push(["Cost","Spaces","Profile","Hits","PTs","DMG","Description","Int","Blk","Del","Opn","ST","EN","AG","IN","CL"]);
    for (const s of this.systems) {
      if (!s.desc && !s.spaces) continue;
      rows.push([s.extraCPs||0, s.spaces, this.sysProfileDisplay(s), this.sysHits(s),
        this.sysBaseCPs(s), s.dmg||"", s.desc||"",
        s.integral?1:0, s.bulky||0, s.delicate||0, s.open?1:0,
        s.adjST||0, s.adjEN||0, s.adjAG||0, s.adjIN||0, s.adjCL||0]);
    }
    return rows.map(r => r.map(c => `"${c}"`).join(",")).join("\n");
  }
}
