// mp-vehicle.js v3.2.0 — Walls data model, hull auto-trace, wall serialization

class Vehicle {
  constructor() {
    this.name = "";
    this.model = "";
    this.operator = "";
    this.basicCost = 15;
    this.techMod = 0;
    this.maneuverMod = 0;
    this.wontExplode = false;
    this.isBase = false;
    this.systems = [];
    this.keyEntries = [];
    this.pictureData = "";
    this.pictureHeight = 120;
    this.silhouette = null; // { data, gx, gy, gw, gh, rot }
    this.armorKin = 3;
    this.armorEng = 3;
    this.armorBio = 3;
    this.armorEnt = 3;
    this.armorPsy = 0;
    this.currentHits = null;  // null = track max
    this.currentPower = null; // null = track max
    this.walls = []; // [{gx, gy, edge:"t"|"l", type:"wall"|"door"|"hatch"}]
    this._remainingSys = { id: "remaining", desc: "Remaining", spaces: 0, cells: [] };
    this._nextId = 1;
    this._nextKeyId = 1;
  }

  get chassis() { return MP.lookupChassis(this.basicCost); }
  get totalSpaces() { return this.chassis.sp; }
  get allocatedSpaces() { return this.systems.reduce((s, sys) => s + (sys.spaces || 0), 0); }
  get remainingSpaces() { return Math.max(0, this.totalSpaces - this.allocatedSpaces - this._remainingSys.cells.length); }

  // Special system for remaining/unallocated spaces (not in systems array)
  getRemainingSys() {
    return this._remainingSys;
  }

  addSystem() {
    const sys = {
      id: this._nextId++,
      spaces: 0, extraCPs: 0, desc: "", dmg: "",
      cells: [],
      integral: false, bulky: 0, delicate: 0, open: false, hideLabels: false,
      adjST: 0, adjEN: 0, adjAG: 0, adjIN: 0, adjCL: 0,
      abilityData: null, // structured dialog state for edit mode
    };
    this.systems.push(sys);
    return sys;
  }

  findSystem(id) {
    if (id === "remaining") return this._remainingSys;
    return this.systems.find(s => s.id === id) || null;
  }

  paintCell(sysId, gx, gy) {
    if (this.cellAt(gx, gy)) return false;
    if (sysId === "remaining") {
      const rem = this._remainingSys;
      if (this.remainingSpaces <= 0) return false;
      rem.cells.push({ gx, gy });
      return true;
    }
    const sys = this.findSystem(sysId);
    if (!sys || sys.integral || sys.cells.length >= sys.spaces) return false;
    sys.cells.push({ gx, gy });
    return true;
  }

  unpaintCell(gx, gy) {
    for (const sys of this.systems) {
      const idx = sys.cells.findIndex(c => c.gx === gx && c.gy === gy);
      if (idx >= 0) { sys.cells.splice(idx, 1); return sys; }
    }
    // Check remaining system
    const rem = this._remainingSys;
    const ri = rem.cells.findIndex(c => c.gx === gx && c.gy === gy);
    if (ri >= 0) { rem.cells.splice(ri, 1); return rem; }
    return null;
  }

  cellAt(gx, gy) {
    for (const sys of this.systems)
      if (sys.cells.some(c => c.gx === gx && c.gy === gy)) return sys;
    if (this._remainingSys.cells.some(c => c.gx === gx && c.gy === gy)) return this._remainingSys;
    return null;
  }

  cellObjAt(gx, gy) {
    for (const sys of this.systems) {
      const c = sys.cells.find(c => c.gx === gx && c.gy === gy);
      if (c) return { sys, cell: c };
    }
    const rc = this._remainingSys.cells.find(c => c.gx === gx && c.gy === gy);
    if (rc) return { sys: this._remainingSys, cell: rc };
    return null;
  }

  addKeyEntry(label, desc) {
    const entry = { id: this._nextKeyId++, label: label || "", desc: desc || "" };
    this.keyEntries.push(entry);
    return entry;
  }

  // CPs generated by system spaces
  sysBaseCPs(sys) {
    if (!sys.spaces) return 0;
    return MP.lookupSys(sys.spaces).cp;
  }

  // Total CPs for the system after all modifiers
  sysCPs(sys) {
    let cp = this.sysBaseCPs(sys);
    cp += (sys.extraCPs || 0);
    cp += this.techMod;
    // Bulky/Delicate only affect Hits and vehicle cost (via extraCPs), not system CPs
    if (sys.integral) cp = Math.ceil(cp / 2);
    if (sys.open) cp = Math.ceil(cp / 4);
    return Math.max(0, cp);
  }

  sysHits(sys) {
    if (!sys.spaces || sys.integral) return 0;
    let hits = MP.lookupSys(sys.spaces).hits;
    hits += Math.ceil(4.3 * (sys.bulky || 0));
    hits -= Math.ceil(4.3 * (sys.delicate || 0));
    return Math.max(1, hits);
  }

  sysProfile(sys) {
    if (!sys.spaces || sys.integral) return 0;
    return MP.lookupSys(sys.spaces).prof;
  }

  sysProfileDisplay(sys) {
    const p = this.sysProfile(sys);
    if (!p) return "";
    return "x" + (Number.isInteger(p) ? p : p.toFixed(2).replace(/0+$/, "").replace(/\.$/, ""));
  }

  get systemExtraCPs() { return this.systems.reduce((sum, s) => sum + (s.extraCPs || 0), 0); }

  get totalCost() {
    let cost = this.basicCost + this.systemExtraCPs + this.techMod;
    cost += this.maneuverMod;
    if (this.wontExplode) cost += 5;
    if (this.isBase) cost -= 15;
    return cost;
  }

  get st() {
    let v = this.chassis.st;
    for (const s of this.systems) v += (s.adjST || 0);
    return v;
  }
  get en() {
    let v = this.chassis.en;
    for (const s of this.systems) v += (s.adjEN || 0);
    return v;
  }
  get ag() {
    let v = 9;
    for (const s of this.systems) v += (s.adjAG || 0);
    return v;
  }
  get intel() {
    let v = 0;
    for (const s of this.systems) v += (s.adjIN || 0);
    return v;
  }
  get cl() {
    let v = 9;
    for (const s of this.systems) v += (s.adjCL || 0);
    return v;
  }
  get hits() { return this.chassis.hits; }
  get power() { return this.st + this.en + this.ag + this.intel; }
  get handling() { return MP.save(this.ag) - 10; }
  get turnRate() { return 3 + (this.maneuverMod / 5); }
  get armor() { return { kin: this.armorKin, eng: this.armorEng, bio: this.armorBio, ent: this.armorEnt, psy: this.armorPsy }; }
  get explosionDice() {
    if (this.wontExplode) return "None";
    const cp = Math.max(0, this.totalCost);
    const d8s = 1 + Math.floor(cp / 5);
    const rem = cp % 5;
    return rem > 0 ? d8s + "d8+1d4" : d8s + "d8";
  }
  get explosionArea() {
    const r = Math.ceil(this.chassis.prof);
    return r % 2 === 0 ? r + 1 : r;
  }

  // ---- Walls ----
  // Edges are normalized: "t" = top edge of cell (gx,gy), "l" = left edge
  // Bottom of (gx,gy) = top of (gx,gy+1), right of (gx,gy) = left of (gx+1,gy)
  static _normEdge(gx, gy, edge) {
    if (edge === "b") return { gx, gy: gy + 1, edge: "t" };
    if (edge === "r") return { gx: gx + 1, gy, edge: "l" };
    return { gx, gy, edge };
  }

  findWall(gx, gy, edge) {
    const n = Vehicle._normEdge(gx, gy, edge);
    return this.walls.find(w => w.gx === n.gx && w.gy === n.gy && w.edge === n.edge) || null;
  }

  setWall(gx, gy, edge, type) {
    const n = Vehicle._normEdge(gx, gy, edge);
    const idx = this.walls.findIndex(w => w.gx === n.gx && w.gy === n.gy && w.edge === n.edge);
    if (type === null || type === undefined) {
      if (idx >= 0) this.walls.splice(idx, 1);
    } else {
      if (idx >= 0) this.walls[idx].type = type;
      else this.walls.push({ gx: n.gx, gy: n.gy, edge: n.edge, type });
    }
  }

  toggleWall(gx, gy, edge) {
    const existing = this.findWall(gx, gy, edge);
    if (!existing) this.setWall(gx, gy, edge, "wall");
    else if (existing.type === "wall") this.setWall(gx, gy, edge, "door");
    else if (existing.type === "door") this.setWall(gx, gy, edge, "hatch");
    else this.setWall(gx, gy, edge, null); // remove
  }

  clearWalls() { this.walls.length = 0; }

  // Hull auto-trace: add walls on exterior edges of all painted cells
  autoTraceHull() {
    const occupied = new Set();
    const allSys = [...this.systems, this._remainingSys];
    for (const sys of allSys) {
      for (const c of sys.cells) occupied.add(`${c.gx},${c.gy}`);
    }
    if (!occupied.size) return;
    // Remove existing hull walls (all walls that border empty space)
    // Then re-add them. Preserve interior walls.
    const isOccupied = (gx, gy) => occupied.has(`${gx},${gy}`);
    // Collect all exterior edges
    const exteriorEdges = [];
    for (const key of occupied) {
      const [gx, gy] = key.split(",").map(Number);
      if (!isOccupied(gx, gy - 1)) exteriorEdges.push({ gx, gy, edge: "t" });
      if (!isOccupied(gx, gy + 1)) exteriorEdges.push({ gx, gy, edge: "b" });
      if (!isOccupied(gx - 1, gy)) exteriorEdges.push({ gx, gy, edge: "l" });
      if (!isOccupied(gx + 1, gy)) exteriorEdges.push({ gx, gy, edge: "r" });
    }
    // Normalize and dedupe
    const edgeSet = new Set();
    for (const e of exteriorEdges) {
      const n = Vehicle._normEdge(e.gx, e.gy, e.edge);
      edgeSet.add(`${n.gx},${n.gy},${n.edge}`);
    }
    // Remove old hull walls (exterior edges), preserve interior
    const interiorWalls = this.walls.filter(w => {
      const key = `${w.gx},${w.gy},${w.edge}`;
      return !edgeSet.has(key); // not an exterior edge
    });
    // Also preserve doors/hatches on exterior that user placed
    const preservedExterior = this.walls.filter(w => {
      const key = `${w.gx},${w.gy},${w.edge}`;
      return edgeSet.has(key) && w.type !== "wall";
    });
    const preservedKeys = new Set(preservedExterior.map(w => `${w.gx},${w.gy},${w.edge}`));
    // Build new wall list
    this.walls = [...interiorWalls, ...preservedExterior];
    for (const key of edgeSet) {
      if (!preservedKeys.has(key)) {
        const [gx, gy, edge] = key.split(",");
        this.walls.push({ gx: +gx, gy: +gy, edge, type: "wall" });
      }
    }
  }

  toJSON() {
    return {
      version: 10, type: "mp-vehicle",
      name: this.name, model: this.model, operator: this.operator,
      basicCost: this.basicCost, techMod: this.techMod,
      maneuverMod: this.maneuverMod, wontExplode: this.wontExplode,
      isBase: this.isBase, systems: this.systems,
      keyEntries: this.keyEntries, pictureData: this.pictureData,
      pictureHeight: this.pictureHeight, silhouette: this.silhouette,
      remainingCells: this._remainingSys.cells,
      walls: this.walls,
      armorKin: this.armorKin, armorEng: this.armorEng,
      armorBio: this.armorBio, armorEnt: this.armorEnt, armorPsy: this.armorPsy,
      currentHits: this.currentHits, currentPower: this.currentPower,
    };
  }

  fromJSON(data) {
    this.name = data.name || "";
    this.model = data.model || "";
    this.operator = data.operator || "";
    this.basicCost = data.basicCost ?? (data.chassisIdx != null ? MP.CHASSIS[data.chassisIdx]?.cp ?? 15 : 15);
    this.techMod = data.techMod || 0;
    this.maneuverMod = data.maneuverMod || 0;
    this.wontExplode = data.wontExplode || false;
    this.isBase = data.isBase || false;
    this.pictureData = data.pictureData || "";
    this.pictureHeight = data.pictureHeight || 120;
    this.silhouette = data.silhouette || null;
    this.armorKin = data.armorKin ?? 3;
    this.armorEng = data.armorEng ?? 3;
    this.armorBio = data.armorBio ?? 3;
    this.armorEnt = data.armorEnt ?? 3;
    this.armorPsy = data.armorPsy ?? 0;
    this.currentHits = data.currentHits ?? null;
    this.currentPower = data.currentPower ?? null;
    this.systems = (data.systems || []).map(s => {
      s.cells = s.cells || [];
      s.extraCPs = s.extraCPs || 0;
      s.integral = s.integral || false;
      if (s.integral) s.cells = []; // integral systems can't have painted cells
      else if (s.spaces && s.cells.length > s.spaces) s.cells.length = s.spaces;
      s.bulky = s.bulky || 0; s.delicate = s.delicate || 0;
      s.open = s.open || false;
      s.hideLabels = s.hideLabels || false;
      s.adjST = s.adjST || 0; s.adjEN = s.adjEN || 0;
      s.adjAG = s.adjAG || 0; s.adjIN = s.adjIN || 0;
      s.adjCL = s.adjCL || 0;
      s.abilityData = s.abilityData || null;
      return s;
    });
    this.keyEntries = data.keyEntries || [];
    this.walls = (data.walls || []).map(w => ({ gx: w.gx, gy: w.gy, edge: w.edge, type: w.type || "wall" }));
    this._remainingSys = { id: "remaining", desc: "Remaining", spaces: 0, cells: data.remainingCells || [] };
    // Trim excess remaining cells if they exceed available space (e.g. from older saves)
    const maxRemCells = Math.max(0, this.totalSpaces - this.allocatedSpaces);
    if (this._remainingSys.cells.length > maxRemCells) {
      this._remainingSys.cells.length = maxRemCells;
    }
    this._nextId = Math.max(1, ...this.systems.map(s => s.id), 0) + 1;
    this._nextKeyId = Math.max(1, ...this.keyEntries.map(k => k.id), 0) + 1;
  }

  toCSV() {
    const rows = [];
    rows.push(["Name", this.name]);
    rows.push(["Basic Cost", this.basicCost]);
    rows.push(["Total Cost", this.totalCost]);
    rows.push(["System Spaces", this.totalSpaces]);
    rows.push(["ST", this.st]); rows.push(["EN", this.en]);
    rows.push(["AG", this.ag]); rows.push(["IN", this.intel]); rows.push(["CL", this.cl]);
    rows.push([]);
    rows.push(["Cost","Spaces","Profile","Hits","PTs","DMG","Description","Int","Blk","Del","Opn","ST","EN","AG","IN","CL"]);
    for (const s of this.systems) {
      if (!s.desc && !s.spaces) continue;
      rows.push([s.extraCPs||0, s.spaces, this.sysProfileDisplay(s), this.sysHits(s),
        this.sysBaseCPs(s), s.dmg||"", s.desc||"",
        s.integral?1:0, s.bulky||0, s.delicate||0, s.open?1:0,
        s.adjST||0, s.adjEN||0, s.adjAG||0, s.adjIN||0, s.adjCL||0]);
    }
    if (this.walls.length) {
      rows.push([]);
      rows.push(["Wall GX","Wall GY","Edge","Type"]);
      for (const w of this.walls) rows.push([w.gx, w.gy, w.edge, w.type]);
    }
    return rows.map(r => r.map(c => `"${c}"`).join(",")).join("\n");
  }
}
